baseURL = 'https://melissabekirova04.github.io/Portifolio/'
locale = 'da-DK'
title = 'Melissa Bekirova | Developer Portfolio'
theme = 'PaperMod'

[params]
description = 'Min developer portfolio'
author = 'Melissa Bekirova'
defaultTheme = 'auto'
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[[menu.main]]
identifier = 'projects'
name = 'Projekter'
url = '/projects/'
weight = 10


[[menu.main]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/Melissabekirova04/Portifolio'
weight = 30